# Generated by Django 5.0.7 on 2025-01-14 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modello', models.CharField(max_length=50)),
                ('proprietario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vigile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('matricola', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contravvenzione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('luogo', models.CharField(max_length=200)),
                ('tipo_infrazione', models.CharField(max_length=100)),
                ('pagata', models.BooleanField(default=False)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.auto')),
                ('vigile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vigile')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('importo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contravvenzione', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.contravvenzione')),
            ],
        ),
    ]
