# Generated by Django 5.0.7 on 2025-01-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione_evento', models.CharField(max_length=200)),
                ('datetime', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name': 'Vigile', 'verbose_name_plural': 'Vigili'},
        ),
        migrations.AlterModelOptions(
            name='contravvenzione',
            options={'verbose_name': 'Vigile', 'verbose_name_plural': 'Vigili'},
        ),
        migrations.AlterModelOptions(
            name='pagamento',
            options={'verbose_name': 'Vigile', 'verbose_name_plural': 'Vigili'},
        ),
        migrations.AlterModelOptions(
            name='vigile',
            options={'verbose_name': 'Vigile', 'verbose_name_plural': 'Vigili'},
        ),
        migrations.RenameField(
            model_name='contravvenzione',
            old_name='luogo',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='contravvenzione',
            name='data',
        ),
        migrations.RemoveField(
            model_name='contravvenzione',
            name='ora',
        ),
    ]
