# Generated by Django 5.0.7 on 2025-01-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_log_alter_auto_options_alter_contravvenzione_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name': 'Auto', 'verbose_name_plural': 'Auto'},
        ),
        migrations.AlterModelOptions(
            name='contravvenzione',
            options={'verbose_name': 'Contravvenzione', 'verbose_name_plural': 'Contravvenzioni'},
        ),
        migrations.AlterModelOptions(
            name='pagamento',
            options={'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamenti'},
        ),
        migrations.AddField(
            model_name='contravvenzione',
            name='luogo',
            field=models.CharField(default='Errore', max_length=200),
        ),
    ]
