# Generated by Django 5.0.7 on 2025-01-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_auto_options_alter_contravvenzione_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contravvenzione',
            name='pagata',
        ),
        migrations.AddField(
            model_name='contravvenzione',
            name='importo',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
    ]
