# Generated by Django 5.0.7 on 2025-01-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_contravvenzione_pagata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='proprietario',
            field=models.CharField(default='Non presente', max_length=100),
        ),
    ]
